### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by adwoodworth** [SIMO-io/simo#2]
* SIMO.io version:
* Python version:
* Operating System:

### Description

The heading for Single Sign In Authorization uses the word "sing" instead of "sign".  This error is made multiple times:
https://simo.io/documentation/
https://simo.io/documentation/users.html#single-sing-in-authorization

### What I Did

I went to this URL https://simo.io/documentation/ and this URL
https://simo.io/documentation/users.html#single-sing-in-authorization

**Comment by Simanas** [comment]
Fixed. Thanks for pointing it out!
